### ISSUE TITLE
Benefit over recursiveUpdate?

### ISSUE THREAD

**Issue by jorsn** [masaeedu/nix-optics#3]
What's the benefit of this over `recursiveUpdate`?

**Comment by masaeedu** [comment]
Well for one thing you can use it to overwrite a deeply nested attrset as well as non-attrsets. The former is not supported by `recursiveUpdate`.

That aside, they're profunctor optics: so you can do all the stuff with them that you can with profunctor optics. You can:

- pass them around
- compose them
- use them to read deeply nested fields
- use them to write deeply nested fields (this is the only feature `recursiveUpdate` supports afaict)
- use them to modify deeply nested fields (with access to the original value)
- instantiate them at any suitable profunctor (the previous three bullet points are examples)
